spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: kitaecoding999@gmail.com
    password: drlc tkcf lhug fazv
    thymeleaf:
      cache: false
      prefix: classpath:/templates
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  firebase-bucket: cauclub-be86c.appspot.com